'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var lr = require('@lezer/lr');
var language = require('@codemirror/language');
var highlight = require('@lezer/highlight');

// This file was generated by lezer-generator. You probably shouldn't edit it.
const parser = lr.LRParser.deserialize({
  version: 14,
  states: "!WQYQPOOOeQPO'#CbOOQO'#Cg'#CgOOQO'#Cc'#CcQYQPOOOOQO,58|,58|OsQPO,58|OOQO-E6a-E6aOOQO1G.h1G.h",
  stateData: "!R~OYOSPOS~ORQOTPO[QO~ORQOSTOTPO[QO~ORQOSWOTPO[QO~O",
  goto: "s[PPPPPP]cPPPmXQOPSUQSOQUPTVSUXROPSU",
  nodeNames: "⚠ LineComment Program String } { Application",
  maxTerm: 12,
  nodeProps: [
    ["openedBy", 4,"{"],
    ["closedBy", 5,"}"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "%g~RXXYnYZn]^npqnrs!Pst#m#V#W$U#o#p%]#q#r%b~sSY~XYnYZn]^npqn~!SVOr!Prs!is#O!P#O#P!n#P;'S!P;'S;=`#g<%lO!P~!nOR~~!qRO;'S!P;'S;=`!z;=`O!P~!}WOr!Prs!is#O!P#O#P!n#P;'S!P;'S;=`#g;=`<%l!P<%lO!P~#jP;=`<%l!P~#rSP~OY#mZ;'S#m;'S;=`$O<%lO#m~$RP;=`<%l#m~$XP#c#d$[~$_P#a#b$b~$eP#d#e$h~$kP#c#d$n~$qP#b#c$t~$wP#X#Y$z~$}P#b#c%Q~%TP#h#i%W~%]O[~~%bOT~~%gOS~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
});

const FreyaLanguage = language.LRLanguage.define({
    parser: parser.configure({
        props: [
            language.indentNodeProp.add({
                Application: language.delimitedIndent({ closing: "}", align: false })
            }),
            language.foldNodeProp.add({
                Application: language.foldInside
            }),
            highlight.styleTags({
                keyword: highlight.tags.keyword,
                String: highlight.tags.string,
                LineComment: highlight.tags.lineComment,
                "{ }": highlight.tags.paren
            })
        ]
    }),
    languageData: {
        commentTokens: { line: "#" }
    }
});
function Freya() {
    return new language.LanguageSupport(FreyaLanguage);
}

exports.Freya = Freya;
exports.FreyaLanguage = FreyaLanguage;
